export const featuredRecipes = [
  {
    id: "1",
    title: "Asian white noodle with extra seafood",
    author: "Someone",
    authorAvatar: "https://i.pravatar.cc/150?img=11",
    time: "20 Min",
    image: "https://images.unsplash.com/photo-1582878826629-29b7ad1cb431?q=80&w=600&auto=format&fit=crop",
    backgroundColor: "#FBA82E", // Orange/Yellow
  },
  {
    id: "2",
    title: "Healthy Taco Salad with fresh vegetable",
    author: "someone",
    authorAvatar: "https://i.pravatar.cc/150?img=5",
    time: "15 Min",
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?q=80&w=600&auto=format&fit=crop",
    backgroundColor: "#F28C28", // Slightly darker orange
  },
];

export const categories = [
  { id: "1", name: "Breakfast" },
  { id: "2", name: "Lunch" },
  { id: "3", name: "Dinner" },
  { id: "4", name: "Midnight Snack" },
  { id: "5", name: "Quick Bites" },
];

export const recommendedRecipes = [
  {
    id: "r1",
    title: "Avocado Toast with Egg",
    time: "10 Min",
    cookingMinutes: 10,
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=600&auto=format&fit=crop",
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-cooking-in-a-modern-kitchen-40082-large.mp4",
    rating: 4.8,
    categoryTag: "Breakfast Special",
    ingredientsCount: 5,
    authorAvatar: "https://i.pravatar.cc/150?img=1",
    authorName: "Sarah Chen",
    difficulty: "Easy",
    description: "A perfectly simple yet satisfying breakfast. Creamy avocado is spread over toasted sourdough and topped with a runny fried egg, chili flakes, and a drizzle of olive oil.",
    nutrition: { calories: 320, carbs: 28, protein: 14, fat: 18 },
    servings: 2,
    ingredients: [
      { name: "Sourdough Bread", quantity: "2 slices" },
      { name: "Avocado", quantity: "1 ripe" },
      { name: "Egg", quantity: "2x pcs" },
      { name: "Chili Flakes", quantity: "1 tsp" },
      { name: "Olive Oil", quantity: "1 tbsp" },
    ],
    steps: [
      { step: 1, instruction: "Toast the sourdough slices until golden and crispy." },
      { step: 2, instruction: "Halve the avocado, remove the pit, and mash the flesh with a fork. Season with salt and pepper." },
      { step: 3, instruction: "Fry the eggs in olive oil over medium heat until the whites are set but yolks are still runny." },
      { step: 4, instruction: "Spread the mashed avocado generously over each toast slice." },
      { step: 5, instruction: "Place the fried egg on top, sprinkle with chili flakes, and serve immediately." },
    ],
  },
  {
    id: "r2",
    title: "Classic Pancakes with Syrup",
    time: "20 Min",
    cookingMinutes: 20,
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1528207776546-384111d017e1?q=80&w=600&auto=format&fit=crop",
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-hand-cutting-an-avocado-40084-large.mp4",
    rating: 4.6,
    categoryTag: "Sweet Breakfast",
    ingredientsCount: 7,
    authorAvatar: "https://i.pravatar.cc/150?img=2",
    authorName: "Emily Park",
    difficulty: "Easy",
    description: "Fluffy, golden pancakes stacked high and drizzled with warm maple syrup. A classic American breakfast that never gets old. Serve with fresh berries and a pat of butter.",
    nutrition: { calories: 450, carbs: 62, protein: 10, fat: 18 },
    servings: 4,
    ingredients: [
      { name: "All-Purpose Flour", quantity: "1.5 cups" },
      { name: "Milk", quantity: "1.25 cups" },
      { name: "Egg", quantity: "1x pcs" },
      { name: "Butter", quantity: "3 tbsp" },
      { name: "Sugar", quantity: "2 tbsp" },
      { name: "Baking Powder", quantity: "1.5 tsp" },
      { name: "Maple Syrup", quantity: "to taste" },
    ],
    steps: [
      { step: 1, instruction: "Whisk together flour, sugar, baking powder, and a pinch of salt in a large bowl." },
      { step: 2, instruction: "In a separate bowl, mix milk, melted butter, and the egg." },
      { step: 3, instruction: "Pour the wet ingredients into the dry and stir until just combined. Do not overmix." },
      { step: 4, instruction: "Heat a non-stick pan over medium heat. Pour ¼ cup batter per pancake." },
      { step: 5, instruction: "Cook until bubbles form on the surface, then flip and cook for another 1–2 minutes." },
      { step: 6, instruction: "Stack and serve with warm maple syrup and fresh berries." },
    ],
  },
  {
    id: "r3",
    title: "Spicy Ramen Noodle Soup",
    time: "25 Min",
    cookingMinutes: 25,
    spiceLevel: 4,
    image: "https://images.unsplash.com/photo-1557872943-16a5ac26437e?q=80&w=600&auto=format&fit=crop",
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-chef-preparing-a-fresh-vegetable-salad-40081-large.mp4",
    rating: 4.9,
    categoryTag: "Quick Lunch",
    ingredientsCount: 9,
    authorAvatar: "https://i.pravatar.cc/150?img=3",
    authorName: "Kenji Tanaka",
    difficulty: "Medium",
    description: "A rich, deeply flavored ramen with a spicy miso broth, tender sliced pork, soft-boiled eggs, and fresh vegetables. Comfort food at its absolute best.",
    nutrition: { calories: 520, carbs: 55, protein: 28, fat: 22 },
    servings: 2,
    ingredients: [
      { name: "Ramen Noodles", quantity: "200g" },
      { name: "Chicken Broth", quantity: "4 cups" },
      { name: "Miso Paste", quantity: "3 tbsp" },
      { name: "Soy Sauce", quantity: "2 tbsp" },
      { name: "Soft-boiled Egg", quantity: "2x pcs" },
      { name: "Sliced Pork Belly", quantity: "150g" },
      { name: "Green Onion", quantity: "2 stalks" },
      { name: "Chili Oil", quantity: "1 tbsp" },
      { name: "Nori Sheets", quantity: "2x pcs" },
    ],
    steps: [
      { step: 1, instruction: "Bring chicken broth to a boil. Whisk in miso paste and soy sauce until dissolved." },
      { step: 2, instruction: "Cook the ramen noodles according to package directions. Drain and set aside." },
      { step: 3, instruction: "Sear sliced pork belly in a hot pan until caramelized on both sides." },
      { step: 4, instruction: "Divide noodles into bowls. Ladle the hot miso broth over them." },
      { step: 5, instruction: "Top with sliced pork, halved soft-boiled eggs, green onion, nori, and a drizzle of chili oil." },
    ],
  },
  {
    id: "r4",
    title: "Grilled Salmon with Asparagus",
    time: "30 Min",
    cookingMinutes: 30,
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=600&auto=format&fit=crop",
    rating: 4.7,
    categoryTag: "Weeknight Dinner",
    ingredientsCount: 6,
    authorAvatar: "https://i.pravatar.cc/150?img=4",
    authorName: "Marco Rossi",
    difficulty: "Easy",
    description: "Perfectly seared salmon fillets served alongside tender grilled asparagus. A light, healthy, and elegant dinner ready in just 30 minutes.",
    nutrition: { calories: 380, carbs: 8, protein: 42, fat: 20 },
    servings: 2,
    ingredients: [
      { name: "Salmon Fillet", quantity: "2x pcs" },
      { name: "Asparagus", quantity: "1 bunch" },
      { name: "Lemon", quantity: "1x pcs" },
      { name: "Olive Oil", quantity: "2 tbsp" },
      { name: "Garlic", quantity: "3 cloves" },
      { name: "Fresh Dill", quantity: "2 tbsp" },
    ],
    steps: [
      { step: 1, instruction: "Preheat the grill to medium-high heat. Pat the salmon fillets dry with paper towels." },
      { step: 2, instruction: "Season salmon with salt, pepper, minced garlic, and a drizzle of olive oil." },
      { step: 3, instruction: "Toss asparagus spears in olive oil, salt, and pepper." },
      { step: 4, instruction: "Grill salmon skin-side down for 4–5 minutes, flip, and cook another 3–4 minutes." },
      { step: 5, instruction: "Grill asparagus alongside for 3–4 minutes, turning occasionally." },
      { step: 6, instruction: "Plate together. Squeeze fresh lemon juice over the top, garnish with dill." },
    ],
  },
  {
    id: "r5",
    title: "Beef Nihari Special",
    time: "120 Min",
    cookingMinutes: 120,
    spiceLevel: 5,
    image: "https://images.unsplash.com/photo-1544025162-811114cd3b51?q=80&w=600&auto=format&fit=crop",
    rating: 4.9,
    categoryTag: "Traditional Dinner",
    ingredientsCount: 14,
    authorAvatar: "https://i.pravatar.cc/150?img=5",
    authorName: "Chef Usman",
    difficulty: "Hard",
    description: "A deeply aromatic, slow-cooked beef stew from the Mughlai tradition. The tender, fall-off-the-bone meat is simmered for hours in a complex blend of whole spices. Best served with naan and garnished with fresh ginger and cilantro.",
    nutrition: { calories: 650, carbs: 12, protein: 48, fat: 46 },
    servings: 6,
    ingredients: [
      { name: "Beef Shank", quantity: "1 kg" },
      { name: "Onion", quantity: "3 large" },
      { name: "Ginger Paste", quantity: "2 tbsp" },
      { name: "Garlic Paste", quantity: "2 tbsp" },
      { name: "Nihari Masala", quantity: "4 tbsp" },
      { name: "Wheat Flour", quantity: "2 tbsp" },
      { name: "Cooking Oil", quantity: "½ cup" },
      { name: "Salt", quantity: "to taste" },
      { name: "Turmeric", quantity: "1 tsp" },
      { name: "Red Chili Powder", quantity: "2 tsp" },
      { name: "Bone Marrow", quantity: "200g" },
      { name: "Fresh Ginger", quantity: "2 inch" },
      { name: "Green Chilies", quantity: "4x pcs" },
      { name: "Fresh Cilantro", quantity: "1 bunch" },
    ],
    steps: [
      { step: 1, instruction: "Heat oil in a large pot. Fry sliced onions until deep golden brown." },
      { step: 2, instruction: "Add ginger-garlic paste and cook for 2 minutes until fragrant." },
      { step: 3, instruction: "Add beef shank pieces and sear on all sides for 5 minutes." },
      { step: 4, instruction: "Add nihari masala, turmeric, red chili powder, and salt. Stir to coat the meat evenly." },
      { step: 5, instruction: "Pour in 8 cups of water. Bring to a boil, then reduce to a low simmer." },
      { step: 6, instruction: "Cover and cook on low heat for 2–3 hours until the meat is fall-off-the-bone tender." },
      { step: 7, instruction: "Mix wheat flour with ½ cup water to make a slurry. Stir into the pot to thicken the gravy." },
      { step: 8, instruction: "Serve hot, garnished with julienned ginger, green chilies, cilantro, and a squeeze of lemon." },
    ],
  },
  {
    id: "r6",
    title: "Chicken Biryani",
    time: "60 Min",
    cookingMinutes: 60,
    spiceLevel: 4,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=600&auto=format&fit=crop",
    rating: 4.9,
    categoryTag: "Feast Dinner",
    ingredientsCount: 18,
    authorAvatar: "https://i.pravatar.cc/150?img=6",
    authorName: "Nadia Hussain",
    difficulty: "Hard",
    description: "The king of South Asian cuisine. Layers of fragrant basmati rice and spiced chicken, slow-cooked together with saffron, fried onions, and fresh herbs. Every bite is a celebration.",
    nutrition: { calories: 580, carbs: 65, protein: 35, fat: 18 },
    servings: 6,
    ingredients: [
      { name: "Chicken", quantity: "1 kg" },
      { name: "Basmati Rice", quantity: "3 cups" },
      { name: "Yogurt", quantity: "1 cup" },
      { name: "Onion", quantity: "4 large" },
      { name: "Tomato", quantity: "2 medium" },
      { name: "Ginger Garlic Paste", quantity: "3 tbsp" },
      { name: "Green Chilies", quantity: "6x pcs" },
      { name: "Fresh Mint", quantity: "½ cup" },
      { name: "Fresh Cilantro", quantity: "½ cup" },
      { name: "Biryani Masala", quantity: "3 tbsp" },
      { name: "Saffron Strands", quantity: "¼ tsp" },
      { name: "Warm Milk", quantity: "¼ cup" },
      { name: "Cooking Oil", quantity: "½ cup" },
      { name: "Whole Spices", quantity: "1 tbsp" },
      { name: "Bay Leaves", quantity: "3x pcs" },
      { name: "Salt", quantity: "to taste" },
      { name: "Red Chili Powder", quantity: "1 tsp" },
      { name: "Lemon Juice", quantity: "2 tbsp" },
    ],
    steps: [
      { step: 1, instruction: "Soak basmati rice in water for 30 minutes. Parboil with whole spices and bay leaves until 70% cooked. Drain." },
      { step: 2, instruction: "Fry sliced onions in oil until deep golden brown. Remove half for garnish." },
      { step: 3, instruction: "In the same pot, add ginger-garlic paste and cook for 2 minutes." },
      { step: 4, instruction: "Add chicken, yogurt, biryani masala, red chili powder, salt, and tomatoes. Cook for 15 minutes." },
      { step: 5, instruction: "Layer the parboiled rice over the chicken. Sprinkle mint, cilantro, fried onions, and saffron milk on top." },
      { step: 6, instruction: "Seal the pot with foil and a tight lid. Cook on the lowest heat for 25 minutes (dum)." },
      { step: 7, instruction: "Gently mix layers before serving. Garnish with boiled eggs and fried onions." },
    ],
  },
  {
    id: "r7",
    title: "Chocolate Lava Cake",
    time: "40 Min",
    cookingMinutes: 40,
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?q=80&w=600&auto=format&fit=crop",
    rating: 4.8,
    categoryTag: "Dessert",
    ingredientsCount: 8,
    authorAvatar: "https://i.pravatar.cc/150?img=7",
    authorName: "Pierre Laurent",
    difficulty: "Medium",
    description: "An indulgent French classic. Break through the delicate chocolate shell to reveal a warm, molten chocolate center that flows like lava. Serve with a scoop of vanilla ice cream.",
    nutrition: { calories: 480, carbs: 42, protein: 8, fat: 32 },
    servings: 4,
    ingredients: [
      { name: "Dark Chocolate", quantity: "200g" },
      { name: "Butter", quantity: "100g" },
      { name: "Eggs", quantity: "3x pcs" },
      { name: "Sugar", quantity: "¼ cup" },
      { name: "All-Purpose Flour", quantity: "2 tbsp" },
      { name: "Vanilla Extract", quantity: "1 tsp" },
      { name: "Cocoa Powder", quantity: "for dusting" },
      { name: "Vanilla Ice Cream", quantity: "to serve" },
    ],
    steps: [
      { step: 1, instruction: "Preheat oven to 220°C (425°F). Grease 4 ramekins and dust with cocoa powder." },
      { step: 2, instruction: "Melt dark chocolate and butter together in a double boiler until smooth." },
      { step: 3, instruction: "In a separate bowl, whisk eggs and sugar until pale and fluffy." },
      { step: 4, instruction: "Fold the chocolate mixture into the egg mixture. Gently fold in the flour and vanilla." },
      { step: 5, instruction: "Divide batter among the ramekins. Bake for exactly 12–14 minutes." },
      { step: 6, instruction: "Let rest for 1 minute, then invert onto plates. Serve immediately with vanilla ice cream." },
    ],
  },
  {
    id: "r8",
    title: "Fresh Caesar Salad",
    time: "15 Min",
    cookingMinutes: 15,
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?q=80&w=600&auto=format&fit=crop",
    rating: 4.5,
    categoryTag: "Healthy Lunch",
    ingredientsCount: 8,
    authorAvatar: "https://i.pravatar.cc/150?img=8",
    authorName: "Julia Morris",
    difficulty: "Easy",
    description: "Crisp romaine lettuce tossed in a tangy, creamy Caesar dressing, topped with crunchy homemade croutons and shaved Parmesan. A timeless classic that works as a side or a light main.",
    nutrition: { calories: 280, carbs: 18, protein: 12, fat: 19 },
    servings: 2,
    ingredients: [
      { name: "Romaine Lettuce", quantity: "2 heads" },
      { name: "Parmesan Cheese", quantity: "½ cup" },
      { name: "Bread Cubes", quantity: "2 cups" },
      { name: "Caesar Dressing", quantity: "¼ cup" },
      { name: "Lemon Juice", quantity: "1 tbsp" },
      { name: "Garlic", quantity: "2 cloves" },
      { name: "Olive Oil", quantity: "3 tbsp" },
      { name: "Anchovy Fillets", quantity: "3x pcs" },
    ],
    steps: [
      { step: 1, instruction: "Toss bread cubes in olive oil, garlic, and salt. Bake at 190°C for 10 minutes until golden croutons." },
      { step: 2, instruction: "Wash and chop romaine lettuce into bite-sized pieces. Pat dry thoroughly." },
      { step: 3, instruction: "Toss the lettuce with Caesar dressing and lemon juice in a large bowl." },
      { step: 4, instruction: "Top with croutons, shaved Parmesan, and cracked black pepper. Serve immediately." },
    ],
  },
];

export const popularRecipes = [
  {
    id: "3",
    title: "Healthy Taco Salad with fresh vegetable",
    time: "20 Min",
    spiceLevel: 3,
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "4",
    title: "Japanese-style Pancakes Recipe",
    time: "12 Min",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1528207776546-384111d017e1?q=80&w=600&auto=format&fit=crop",
  },
];
